# Generated by Django 4.0.4 on 2022-06-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=9)),
                ('floor_price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('Owners', models.IntegerField()),
                ('items', models.IntegerField()),
                ('blockchain', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('name', models.CharField(max_length=455)),
                ('collection', models.CharField(max_length=255)),
                ('last_price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('currency', models.CharField(max_length=255)),
                ('blockchain', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
